imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BoutiqueBundle/Resources/config/services.yml" }
    - { resource: "@HotellerieBundle/Resources/config/services.yml" }
    - { resource: "@RestaurationBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@CultureBundle/Resources/config/services.yml" }
    - { resource: "@CampementBundle/Resources/config/services.yml" }
    - { resource: "@EvenementBundle/Resources/config/services.yml" }
    - { resource: "@UtilisateurBundle/Resources/config/services.yml" }
    - { resource: "@BaseBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    #parametres globals twig
    globals:
        webmaster: Abdoulaye KAMA

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


#uploading files
vich_uploader:
    db_driver: orm
    mappings:
        image_produit:
            uri_prefix:         /uploads/images/produit
            upload_destination: '%kernel.root_dir%/../web/uploads/images/produit'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        image_article:
            uri_prefix:         /uploads/images/article
            upload_destination: '%kernel.root_dir%/../web/uploads/images/article'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        image_hotel:
            uri_prefix:         /uploads/images/hotel
            upload_destination: '%kernel.root_dir%/../web/uploads/images/hotel'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        image_restaurant:
            uri_prefix:         /uploads/images/restaurant
            upload_destination: '%kernel.root_dir%/../web/uploads/images/restaurant'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        image_diaporama:
            uri_prefix:         /uploads/images/diaporama
            upload_destination: '%kernel.root_dir%/../web/uploads/images/diaporama'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        image_user:
            uri_prefix:         /uploads/images/user
            upload_destination: '%kernel.root_dir%/../web/uploads/images/user'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        image_client:
            uri_prefix:         /uploads/images/client
            upload_destination: '%kernel.root_dir%/../web/uploads/images/client'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true