<?php

namespace CampementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampementRepository extends EntityRepository
{
}
