<?php

namespace BoutiqueBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ElementCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementCommandeRepository extends EntityRepository
{
}
